// Generated by CoffeeScript 1.7.1
(function() {
  jQuery(function() {
    console.log("#   #  #  #   #  ###   ###   #  #   #");
    console.log("## ##  #  ##  #  #  #  #  #  #  ##  #");
    console.log("# # #  #  # # #  #  #  ###   #  # # #");
    console.log("#   #  #  #  ##  #  #  #     #  #  ##");
    console.log("#   #  #  #   #  ###   #     #  #   #\n");
    console.log("%c哈哈，这里被你发现了", "color:#2C9BE2;");
    console.log("平时是不是习惯打开 console 看 :P\n");
    console.log("这个网页只用了一张图片，也就是 logo .");
    console.log("除此之外还利用了哪些 CSS3 特性，你知道吗？");
    return console.log("如果你知道，也写在邮件里吧！ 期待你的联系！");
  });

}).call(this);
